name: airbnb_clone
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  firebase_core: 
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  image_picker:
  flutter_image_compress:
  path_provider: 
  auto_size_text: 
  http: ^1.6.0
  custom_rating_bar: ^3.0.0
  google_maps_flutter: ^2.14.0
  geocoding: 
  flutter_stripe: 
  flutter_dotenv: ^6.0.0  
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Couture
      fonts:
        - asset: assets/fonts/couture.ttf